services:
  runner:
    env_file:
      - .env
    container_name: github-actions
    # image: ghcr.io/jamesonrgrieve-instruction/runner:main
    build:
      context: ./services/gh-actions
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    networks:
      core:
        ipv4_address: 172.20.0.123
