services:
  runner:
    env_file:
      - .env
    container_name: github-actions
    # image: ghcr.io/jamesonrgrieve-instruction/runner:main
    build:
      context: ./services/gh-actions
      dockerfile: Dockerfile
    restart: always
    privileged: true # Required for Docker-in-Docker
    volumes:
      - /var/lib/docker # Docker-in-Docker volume
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M
    networks:
      core:
        ipv4_address: 172.20.0.123
